export const FREE_COUNT = 12;

export type Provider = {
  name: string;
  domain: string;
  value: string;
  category: string;
  tags: string[];
  description: string;
};

export const providers: Provider[] = [
  { name: "AWS", domain: "aws.amazon.com", value: "Up to $100,000", category: "Cloud", tags: ["cloud"], description: "World's leading cloud platform. Up to $100K during the first year." },
  { name: "Google Cloud", domain: "cloud.google.com", value: "Up to $350,000", category: "Cloud", tags: ["cloud", "ai"], description: "Up to $350K for AI startups." },
  { name: "Microsoft Azure", domain: "azure.microsoft.com", value: "Up to $150,000", category: "Cloud", tags: ["cloud", "enterprise"], description: "Microsoft global cloud platform with $150K in credits." },
  { name: "Notion", domain: "notion.so", value: "$6,000", category: "Productivity", tags: ["productivity", "docs"], description: "6 months free Notion Plus worth up to $6,600." },
  { name: "Stripe", domain: "stripe.com", value: "$50,000", category: "Finance", tags: ["finance", "payments"], description: "$50,000 in fee-free processing for new startups." },
  { name: "Cloudflare", domain: "cloudflare.com", value: "Up to $250,000", category: "Networking", tags: ["cloud", "cdn", "security"], description: "Security, performance, and reliability for startups." },
  { name: "HubSpot", domain: "hubspot.com", value: "75% off", category: "CRM", tags: ["crm", "marketing", "sales"], description: "75% off first year of HubSpot marketing and CRM suite." },
  { name: "Intercom", domain: "intercom.com", value: "90% off", category: "Customer Support", tags: ["customer support", "ai"], description: "90% discount on AI-first customer service platform." },
  { name: "Mixpanel", domain: "mixpanel.com", value: "Up to $150,000", category: "Analytics", tags: ["analytics"], description: "Free access for one year, up to $150K value." },
  { name: "Airtable", domain: "airtable.com", value: "$500", category: "Productivity", tags: ["productivity", "database"], description: "$500 in credits for the flexible cloud-based platform." },
  { name: "DigitalOcean", domain: "digitalocean.com", value: "$5,000+", category: "Cloud", tags: ["cloud"], description: "$5K+ in credits plus perks from partners like Stripe." },
  { name: "Databricks", domain: "databricks.com", value: "Up to $50,000", category: "Data & AI", tags: ["big data", "analytics", "ai"], description: "Up to $50K for data, analytics, and AI workloads." },
  { name: "Datadog", domain: "datadoghq.com", value: "$800/year", category: "Monitoring", tags: ["monitoring", "devops"], description: "$800 annually for eligible startups." },
  { name: "Zendesk", domain: "zendesk.com", value: "6 months free", category: "Customer Support", tags: ["customer support", "crm"], description: "6 months free access to Zendesk for qualifying startups." },
  { name: "Algolia", domain: "algolia.com", value: "$10,000", category: "Search", tags: ["search", "api", "dev tools"], description: "$10,000 in credits for 12 months for startups." },
  { name: "Amplitude", domain: "amplitude.com", value: "12 months free", category: "Analytics", tags: ["analytics", "cdp"], description: "Free access to Growth plan for 12 months." },
  { name: "Segment", domain: "segment.com", value: "Up to $50,000", category: "Analytics", tags: ["analytics"], description: "Up to $50K in credits for 2 years for early-stage startups." },
  { name: "Sentry", domain: "sentry.io", value: "6 months free", category: "Monitoring", tags: ["monitoring", "devops", "dev tools"], description: "6 months free on Teams plan plus 10% annual discount." },
  { name: "GitHub", domain: "github.com", value: "20 free seats", category: "Dev Tools", tags: ["dev tools", "collaboration"], description: "20 free seats of GitHub Enterprise for startups." },
  { name: "GitLab", domain: "gitlab.com", value: "20 licenses free", category: "Dev Tools", tags: ["dev tools", "collaboration"], description: "20 GitLab Ultimate licenses for 1 year." },
  { name: "Linear", domain: "linear.app", value: "6 months free", category: "Project Management", tags: ["project management", "workflow"], description: "6 months free on streamlined project management tool." },
  { name: "Miro", domain: "miro.com", value: "$1,000-$1,500", category: "Collaboration", tags: ["collaboration", "design"], description: "$1,000-$1,500 in credits for startups." },
  { name: "Asana", domain: "asana.com", value: "12 months free", category: "Project Management", tags: ["project management", "productivity"], description: "12-month free Advanced plan access for startups." },
  { name: "ClickUp", domain: "clickup.com", value: "$3,000", category: "Productivity", tags: ["productivity", "project management"], description: "$3,000 in ClickUp credits for startups." },
  { name: "Retool", domain: "retool.com", value: "12 months free", category: "Dev Tools", tags: ["dev tools", "low-code", "ai"], description: "Free access to Retool platform for 12 months." },
  { name: "Webflow", domain: "webflow.com", value: "12 months free", category: "No-Code", tags: ["no-code", "web design"], description: "Free CMS site plan for 12 months for startups." },
  { name: "Framer", domain: "framer.com", value: "$2,000", category: "Design", tags: ["design", "no-code", "hosting"], description: "$2,000 in credits for Framer Expert hiring and hosting." },
  { name: "PostHog", domain: "posthog.com", value: "$50,000", category: "Analytics", tags: ["analytics", "dev tools"], description: "$50K in credits for open-source product analytics." },
  { name: "MongoDB", domain: "mongodb.com", value: "$500", category: "Database", tags: ["database"], description: "$500 in credits for MongoDB Atlas." },
  { name: "Redis", domain: "redis.io", value: "$10,000", category: "Database", tags: ["database", "cloud", "dev tools"], description: "$10,000 in Redis credits for startups." },
  { name: "Neon", domain: "neon.tech", value: "$100,000", category: "Database", tags: ["database", "serverless", "cloud"], description: "$100K in Neon serverless PostgreSQL credits." },
  { name: "Pinecone", domain: "pinecone.io", value: "Free Standard Tier", category: "Database", tags: ["ai", "database", "ml"], description: "Free Standard Tier and Pro Support for AI startups." },
  { name: "OpenAI", domain: "openai.com", value: "$25,000", category: "AI", tags: ["ai", "api"], description: "$25,000 in API credit grants for qualifying startups." },
  { name: "Perplexity", domain: "perplexity.ai", value: "$5,000 + 6mo free", category: "AI", tags: ["ai", "llm", "enterprise"], description: "6 months free Enterprise Pro plus $5K in API credits." },
  { name: "ElevenLabs", domain: "elevenlabs.io", value: "$1,500+", category: "AI", tags: ["ai", "speech", "api"], description: "$1,500+ in AI voice generation credits." },
  { name: "AssemblyAI", domain: "assemblyai.com", value: "Up to $150,000", category: "AI", tags: ["ai", "speech", "api"], description: "Up to $150K in free API credits for speech AI startups." },
  { name: "Deepgram", domain: "deepgram.com", value: "Up to $100,000", category: "AI", tags: ["ai", "speech", "api"], description: "Up to $100K in speech recognition credits for 12 months." },
  { name: "Mistral", domain: "mistral.ai", value: "Free API credits", category: "AI", tags: ["ai", "api", "llm"], description: "Free API credits and VIP perks for Mistral AI ambassadors." },
  { name: "Cerebras", domain: "cerebras.ai", value: "Up to $22,500", category: "AI", tags: ["ai", "llm", "gpu", "cloud"], description: "Up to $22.5K in inference credits for AI startups." },
  { name: "Fireworks", domain: "fireworks.ai", value: "Up to $100,000", category: "AI", tags: ["ai", "ml", "llm", "api"], description: "Up to $100K in generative AI inference credits." },
  { name: "Airbyte", domain: "airbyte.com", value: "Up to $75,000", category: "Data", tags: ["cloud", "data", "dev tools"], description: "Up to $75K in Airbyte Cloud credits for YC startups." },
  { name: "Fivetran", domain: "fivetran.com", value: "$50,000", category: "Data", tags: ["analytics", "data", "api"], description: "$50K in free Fivetran data integration credits for 12 months." },
  { name: "Aiven", domain: "aiven.io", value: "Up to $100,000", category: "Cloud", tags: ["cloud", "data", "open source"], description: "Up to $100K in credits for managed open-source data services." },
  { name: "Akamai", domain: "akamai.com", value: "Up to $120,000", category: "Cloud", tags: ["cloud", "edge", "cdn"], description: "Up to $120K during the first year on distributed cloud platform." },
  { name: "IBM Cloud", domain: "ibm.com", value: "Up to $120,000", category: "Cloud", tags: ["cloud", "enterprise"], description: "Up to $120K in enterprise-grade IBM Cloud credits." },
  { name: "Oracle", domain: "oracle.com", value: "$300 free trial", category: "Cloud", tags: ["cloud", "free trial"], description: "$300 free trial plus Always Free Cloud Services." },
  { name: "Vultr", domain: "vultr.com", value: "Up to $100,000", category: "Cloud", tags: ["cloud"], description: "Up to $100K in credits for cloud migration." },
  { name: "Cloudways", domain: "cloudways.com", value: "Up to $50,000", category: "Cloud", tags: ["cloud", "hosting"], description: "Up to $50K in managed cloud hosting credits." },
  { name: "Koyeb", domain: "koyeb.com", value: "Up to $30,000", category: "Cloud", tags: ["cloud", "ai", "gpu"], description: "Up to $30K compute credits for high-performance cloud infra." },
  { name: "Scaleway", domain: "scaleway.com", value: "Up to €36,000", category: "Cloud", tags: ["cloud", "europe"], description: "Up to €36K in credits for 1 year from European cloud provider." },
  { name: "OVH", domain: "ovhcloud.com", value: "Up to €100,000", category: "Cloud", tags: ["cloud", "europe"], description: "Up to €100K in cloud credits for 1 year." },
  { name: "Appwrite", domain: "appwrite.io", value: "$20,000", category: "Dev Tools", tags: ["cloud", "open source", "dev tools"], description: "$20K in Cloud Credits for Startups." },
  { name: "Pulumi", domain: "pulumi.com", value: "Up to $10,000", category: "Dev Tools", tags: ["dev tools", "cloud", "devops"], description: "Up to $10K in Pulumi Credits plus exclusive tech support." },
  { name: "CircleCI", domain: "circleci.com", value: "400K monthly credits", category: "Dev Tools", tags: ["devops", "ci/cd", "open source"], description: "Up to 400,000 monthly credits for CI/CD builds." },
  { name: "Temporal", domain: "temporal.io", value: "$6,000", category: "Dev Tools", tags: ["dev tools", "workflow"], description: "$6,000 in free Temporal Cloud credits." },
  { name: "JetBrains", domain: "jetbrains.com", value: "6 months free", category: "Dev Tools", tags: ["dev tools"], description: "6 months free then 50% discount on developer tools." },
  { name: "Cursor", domain: "cursor.sh", value: "1 year free Pro", category: "Dev Tools", tags: ["dev tools", "ai"], description: "Free 1-year Cursor Pro for students and eligible startups." },
  { name: "Vanta", domain: "vanta.com", value: "Up to $1,000 off", category: "Compliance", tags: ["compliance", "cybersecurity"], description: "Up to $1,000 off SOC 2 and ISO 27001 compliance automation." },
  { name: "Auth0", domain: "auth0.com", value: "1 year free", category: "Dev Tools", tags: ["cybersecurity", "api", "dev tools"], description: "1-year free access to B2B Professional Plan." },
  { name: "Chargebee", domain: "chargebee.com", value: "40% off Y1", category: "Finance", tags: ["finance", "saas", "automation"], description: "40% off year 1 and 20% off year 2 on subscription billing." },
  { name: "Grafana", domain: "grafana.com", value: "Up to €100,000", category: "Monitoring", tags: ["monitoring", "analytics", "devops"], description: "Up to €100K in credits for 1 year." },
  { name: "Statsig", domain: "statsig.com", value: "$50,000", category: "Analytics", tags: ["analytics", "dev tools", "data"], description: "$50K in credits for 12 months on feature shipping platform." },
  { name: "Customer.io", domain: "customer.io", value: "12 months free", category: "Marketing", tags: ["marketing", "automation", "email"], description: "Up to 12 months free access for early-stage startups." },
  { name: "Mailchimp", domain: "mailchimp.com", value: "Free forever", category: "Marketing", tags: ["email", "marketing", "automation"], description: "Free forever plan for up to 500 contacts." },
  { name: "Typeform", domain: "typeform.com", value: "Up to 75% off", category: "Forms", tags: ["forms", "no-code"], description: "Up to 75% discount on annual Business plan." },
  { name: "HeyGen", domain: "heygen.com", value: "Up to 90% off", category: "AI", tags: ["ai", "video", "marketing"], description: "Up to 90% off AI video generation platform." },
  { name: "Mux", domain: "mux.com", value: "$500", category: "Media", tags: ["cdn", "media", "dev tools"], description: "$500 in credits for video infrastructure platform." },
  { name: "Freshworks", domain: "freshworks.com", value: "$3,000", category: "CRM", tags: ["crm", "customer support"], description: "$3,000 in credits for FreshStack startup program." },
  { name: "Attio", domain: "attio.com", value: "Up to 80% off", category: "CRM", tags: ["crm", "saas", "collaboration"], description: "Up to 80% off Annual Pro Plan plus $5,000 credit." },
  { name: "Coda", domain: "coda.io", value: "Up to $1,000", category: "Productivity", tags: ["productivity", "collaboration", "no-code"], description: "6-month free Team plan worth up to $1,000." },
  { name: "Make", domain: "make.com", value: "Up to $1,100", category: "Automation", tags: ["automation", "workflow", "no-code"], description: "Up to $1,100 in operational credits for startups." },
  { name: "n8n", domain: "n8n.io", value: "Startup discount", category: "Automation", tags: ["automation", "no-code", "workflow"], description: "Startup discount on workflow automation platform." },
  { name: "Zapier", domain: "zapier.com", value: "14-day free trial", category: "Automation", tags: ["automation", "workflow", "api"], description: "14-day free Pro trial on no-code automation platform." },
  { name: "Apollo", domain: "apollo.io", value: "50% off annual", category: "Sales", tags: ["sales", "marketing", "b2b"], description: "50% discount on annual Basic/Professional plans." },
  { name: "Clay", domain: "clay.com", value: "1,200 credits/year", category: "Sales", tags: ["data", "sales", "marketing"], description: "100 credits monthly for free on Clay." },
  { name: "Remote", domain: "remote.com", value: "Up to 20% off", category: "HR", tags: ["hr", "compliance", "payroll"], description: "Up to 20% discount on global HR and payroll services." },
  { name: "QuickNode", domain: "quicknode.com", value: "Up to $200,000", category: "Web3", tags: ["blockchain", "web3"], description: "Up to $200K in RaaS credits for blockchain API usage." },
  { name: "Alchemy", domain: "alchemy.com", value: "3 months free", category: "Web3", tags: ["web3", "blockchain"], description: "3 months of free credits for Web3 developer infrastructure." },
  { name: "Stripe Atlas", domain: "stripe.com", value: "$100,000+ perks", category: "Finance", tags: ["finance"], description: "Access to $100K+ in combined partner discounts and credits." },
  { name: "xAI", domain: "x.ai", value: "$150/month", category: "AI", tags: ["api", "ai", "llm"], description: "$150 monthly API credits for Grok models." },
  { name: "Nebius", domain: "nebius.com", value: "Up to $150,000", category: "AI", tags: ["ai", "cloud", "ml"], description: "Up to $150K in cloud credits for AI companies." },
  { name: "1Password", domain: "1password.com", value: "Free Teams account", category: "Security", tags: ["dev tools", "open source", "productivity"], description: "Free unlimited Teams account for open source projects." },
  { name: "LinkedIn", domain: "linkedin.com", value: "75% off 4 months", category: "Marketing", tags: ["social", "sales", "marketing"], description: "75% off Premium subscriptions for four months." },
  { name: "Google Ads", domain: "ads.google.com", value: "Up to $1,500", category: "Advertising", tags: ["advertising", "marketing"], description: "Up to $1,500 in ad credits for new advertisers." },
  { name: "TikTok", domain: "tiktok.com", value: "Up to $1,500", category: "Advertising", tags: ["social", "marketing", "advertising"], description: "Up to $1,500 in matching ad credits." },
  { name: "Reddit Ads", domain: "reddit.com", value: "$500 matched", category: "Advertising", tags: ["advertising", "marketing", "social"], description: "Spend $500, get $500 in matched Reddit ad credit." },
];